name: blocfx
description: A Flutter package that extends flutter_bloc with Effect streams for handling single-shot events and automatic state persistence. Following MVI pattern with hydrated state support.
version: 0.2.0
homepage: https://github.com/fajarxfce/blocfx
repository: https://github.com/fajarxfce/blocfx
issue_tracker: https://github.com/fajarxfce/blofx/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  mocktail: ^1.0.0

flutter:

topics:
  - bloc
  - state-management
  - mvi
  - side-effects
  - flutter
